services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: weather-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  weather-api:
    build:
      context: ./WeatherTelemetryApi
      dockerfile: Dockerfile
    container_name: weather-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__VirtualHost: /
      RabbitMQ__ExchangeName: weather
      Hmac__SecretKey: kocham-wsb
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:


